//
// Created by jglrxavpok on 27/11/2020.
//

#pragma once
#include <glm/glm.hpp>

enum DebugRenderType {
    DEBUG_GBUFFER_DISABLED = 0,
    DEBUG_GBUFFER_ALBEDO,
    DEBUG_GBUFFER_POSITION,
    DEBUG_GBUFFER_DEPTH,
    DEBUG_GBUFFER_NORMAL,
    DEBUG_GBUFFER_METALLIC_ROUGHNESS,
    DEBUG_GBUFFER_EMISSIVE,
    DEBUG_GBUFFER_RANDOMNESS,
    DEBUG_GBUFFER_TANGENT,
    DEBUG_GBUFFER_LIGHTING,
    DEBUG_GBUFFER_MOTION,
    DEBUG_GBUFFER_MOMENTS,
    DEBUG_GBUFFER_ENTITYID,
    DEBUG_GBUFFER_NOISY_LIGHTING,
    DEBUG_POST_TEMPORAL_DENOISE,
    DEBUG_VARIANCE,
    DEBUG_POST_FIREFLY_REJECTION,

    DEBUG_VISIBILITY_BUFFER_FIRST,
    DEBUG_VISIBILITY_BUFFER_TRIANGLES = DEBUG_VISIBILITY_BUFFER_FIRST,
    DEBUG_VISIBILITY_BUFFER_CLUSTERS,
    DEBUG_VISIBILITY_BUFFER_LODS,
    DEBUG_VISIBILITY_BUFFER_SCREEN_ERROR,
    DEBUG_VISIBILITY_BUFFER_LAST = DEBUG_VISIBILITY_BUFFER_SCREEN_ERROR,

};

namespace Carrot {

    struct DebugBufferObject {
        std::uint32_t gBufferType = DEBUG_GBUFFER_DISABLED;
    };
}
