#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#include "raytrace.common.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = 0, rgba32f) uniform image2D image;

layout(location = 0) rayPayloadEXT hitPayload payload;

void main()
{
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(0.1, 0.5, 0.5, 1.0));
}
