#include "PhysicsCharacterComponent.h"

namespace Carrot::ECS {
    PhysicsCharacterComponent::PhysicsCharacterComponent(Carrot::ECS::Entity entity)
            : Carrot::ECS::IdentifiableComponent<PhysicsCharacterComponent>(std::move(entity)) {
        // TODO: autogenerated
    }

    PhysicsCharacterComponent::PhysicsCharacterComponent(const rapidjson::Value& json, Carrot::ECS::Entity entity)
            : PhysicsCharacterComponent(std::move(entity)) {
        // TODO: read from json
    }

    std::unique_ptr <Carrot::ECS::Component> PhysicsCharacterComponent::duplicate(const Carrot::ECS::Entity& newOwner) const {
        auto result = std::make_unique<PhysicsCharacterComponent>(newOwner);
        result->character = character;
        return result;
    }

} // Carrot::ECS